services:
  api:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://savesphere:savespheresecret@postgres:5432/savespheredb?schema=public
      PORT: 4000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  postgres:
    image: postgres:14-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: savesphere
      POSTGRES_PASSWORD: savespheresecret
      POSTGRES_DB: savespheredb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: